# Generated by Django 3.0.7 on 2021-02-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None)),
                ('number', models.CharField(max_length=20)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogPcEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('data_time', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(default='')),
                ('host_name', models.CharField(blank=True, default='', max_length=500)),
                ('hard_name', models.CharField(blank=True, default='', max_length=500)),
                ('os', models.CharField(blank=True, default='', max_length=500)),
                ('secret_net_studio_version', models.CharField(blank=True, default='', max_length=100)),
                ('crypto_pro_version', models.CharField(blank=True, default='', max_length=100)),
                ('vipnet_client_version', models.CharField(blank=True, default='', max_length=100)),
                ('kaspersky_version', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification_pc.Address')),
                ('department', models.ManyToManyField(blank=True, null=True, to='mts.Department')),
                ('ovd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mts.Ovd')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('serial_number', models.CharField(default='', max_length=500)),
                ('inventory_number', models.CharField(default='', max_length=50)),
                ('isUnknownInventoryNumber', models.BooleanField(default=False)),
                ('price_start_up', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, null=True)),
                ('user', models.CharField(blank=True, default='', max_length=100)),
                ('bailee', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('inventory_number_other', models.CharField(blank=True, default='', max_length=100)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('ip_address', models.GenericIPAddressField(default='')),
                ('host_name', models.CharField(blank=True, default='', max_length=500)),
                ('hard_serial_number', models.CharField(blank=True, default='', max_length=500)),
                ('hard_name', models.CharField(blank=True, default='', max_length=500)),
                ('os', models.CharField(blank=True, default='', max_length=500)),
                ('secret_net_studio_version', models.CharField(blank=True, default='', max_length=100)),
                ('crypto_pro_version', models.CharField(blank=True, default='', max_length=100)),
                ('vipnet_client_version', models.CharField(blank=True, default='', max_length=100)),
                ('kaspersky_version', models.CharField(blank=True, default='', max_length=100)),
                ('isApply', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IS_APPLY', 'Применяется'), ('IS_NOT_APPLY', 'Не применяется'), ('PROCESSING', 'Обработка')], default='IS_NOT_APPLY', max_length=15)),
                ('date_apply', models.DateField(blank=True, default=None, null=True)),
                ('date_edit', models.DateField(blank=True, default=None, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('act', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='certification_pc.Act')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mts.Department')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certification_pc.Object')),
                ('ovd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mts.Ovd')),
            ],
        ),
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('note', models.TextField(default='')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certification_pc.Address')),
            ],
        ),
        migrations.CreateModel(
            name='LogConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('data_time', models.DateTimeField(auto_now=True)),
                ('nas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certification_pc.Nas')),
                ('pc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certification_pc.PC')),
            ],
        ),
    ]
