# Generated by Django 3.0.7 on 2021-02-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0003_pc_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date_create', models.DateField()),
                ('date_remove', models.DateField()),
                ('ip_real', models.GenericIPAddressField()),
                ('ip_virtual', models.GenericIPAddressField()),
                ('pc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certification_pc.PC')),
            ],
        ),
    ]
