# Generated by Django 3.0.7 on 2021-02-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0004_vipnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipnet',
            name='date_create',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vipnet',
            name='date_remove',
            field=models.DateField(null=True),
        ),
    ]
