# Generated by Django 3.0.7 on 2021-03-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0005_auto_20210211_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipnet',
            name='isLooked',
            field=models.BooleanField(default=False),
        ),
    ]
