# Generated by Django 3.0.7 on 2021-03-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0006_vipnet_islooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipnet',
            name='last_date_looked',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
