# Generated by Django 3.0.7 on 2021-05-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0007_vipnet_last_date_looked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipnet',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
