# Generated by Django 3.0.7 on 2021-05-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0008_vipnet_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipnetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='vipnet',
            name='vipnet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certification_pc.VipnetType'),
        ),
    ]
