# Generated by Django 3.0.7 on 2021-05-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0009_auto_20210528_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipnet',
            name='isServices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vipnet',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
