# Generated by Django 3.0.7 on 2021-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0010_auto_20210530_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipnet',
            old_name='isLooked',
            new_name='isLocked',
        ),
        migrations.RenameField(
            model_name='vipnet',
            old_name='last_date_looked',
            new_name='last_date_locked',
        ),
        migrations.AddField(
            model_name='logpcedit',
            name='vipnet_identifier',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vipnet',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
