# Generated by Django 3.0.7 on 2021-05-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0011_auto_20210531_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpcedit',
            name='vipnet_identifier',
            field=models.CharField(default='', max_length=10),
        ),
    ]
