# Generated by Django 3.0.7 on 2021-06-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_pc', '0013_auto_20210531_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='date_exclude',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
